### ISSUE TITLE
Downloading routine not working; invalid config parsing

### ISSUE THREAD

**Issue by Connorcivi** [Windows81/Roblox-Freedom-Distribution#11]
Good afternoon people,

So I am currently running the source version of the code since executable keeps returning an error saying unable to load a module. 

Error of module: ModuleNotFoundError: No module named 'tqdm._tqdm_pandas'

Anyways, when running source it works fine but it seems to be unable to connect to the servers to fetch a roblox version, 

It returns with the error: urllib.error.HTTPError: HTTP Error 404: Not F

I am currently digging through the code to see if I can manually download the file. Please let me know what I can do, thank you.

**Comment by Connorcivi** [comment]
I managed to force a skip download by downloading the 7zip myself and extracting it, but for some reason it keeps saying "Joining server, been like this for 20 minutes and on the server console it's saying Initializing Rōblox Cloud Compute.

**Comment by Windows81** [comment]
Stoopid PyInstaller is having compatibility problems with whatever mess I'm
making with Tqdm.

I should fix that later today.

**Comment by Connorcivi** [comment]
Would there be a problem with the client being unable to connect to the server? Keeps saying Not authorized.

**Comment by Connorcivi** [comment]
![RobloxScreenShot20240822_163634489](https://github.com/user-attachments/assets/78a64c71-a158-45c4-a897-22c236cf7a92)

Here's a screenshot just incase you needed it.

**Comment by Windows81** [comment]
Let me know what the server logs are when you run --verbose.

**Comment by Connorcivi** [comment]
Sure, here's the logs. Also another screenshot.

![Screenshot 2024-08-22 210855](https://github.com/user-attachments/assets/8a2730d5-6f75-4326-8704-2c233d11b897)

**Note, this was done twice, tried connecting with client twice.**

```
Initializing Web-Server...
Rōblox installation exists, skipping...
Initializing Rōblox Cloud Compute...
https://localhost:2005/rfd/certificate
1724375039.02492,2bc8,6 Loading AppSettings.xml, current path: C:\Users\conno\Downloads\rfd\rfd\Roblox\v348\Server
1724375039.02791,2bc8,6 CrashReporter Start
Service starting...
1724375039.02791,2bc8,6 setAssetFolder C:\Users\conno\Downloads\rfd\rfd\Roblox\v348\Server\Content\
1724375039.02791,58bc,6 WatcherThread Started
1724375039.03391,2bc8,6 Initializing Roblox Web Service
1724375039.03391,2bc8,6 FetchClientSettingsDataBlocking group "RCCService"
1724375039.45314,2bc8,6 LoadClientSettingsFromFetchedString group: "RCCService"
1724375039.45314,2bc8,6 LoadClientSettingsFromLocal group: "RCCService"
https://localhost:2005/api.GetAllowedSecurityVersions/?apiKey=2b4ba7fc-5843-44cf-b107-ba22d3319dcd
https://localhost:2005/api.GetAllowedMD5Hashes/?apiKey=2b4ba7fc-5843-44cf-b107-ba22d3319dcd
1724375039.88654,2bc8,6 Service Started on port 0
1724375039.89657,2bc8,6 FetchClientSettingsDataBlocking group "RCCService"
1724375040.30985,2bc8,6 LoadClientSettingsFromFetchedString group: "RCCService"
1724375040.30985,2bc8,6 LoadClientSettingsFromLocal group: "RCCService"
1724375040.35292,2bc8,6,GameServer,1818,13058,https://localhost:2005/.127.0.0.1,Test,https://localhost:2005,unknown,Test RCC Executing: [{"Mode": "GameServer", "GameId": 13058, "Settings": {"Type": "Avatar", "PlaceId": 1818, "GameId": "Test", "MachineAddress": "https://localhost:2005", "PlaceFetchUrl": "https://localhost:2005/asset/?id=1818", "MaxPlayers": 2, "PreferredPlayerCapacity": 2, "CharacterAppearance": "https://localhost:2005/v1.1/avatar-fetch", "MaxGameInstances": 1, "GsmInterval": 5, "ApiKey": "", "DataCenterId": "69420", "PlaceVisitAccessKey": "", "UniverseId": 13058, "MatchmakingContextId": 1, "CreatorId": 1, "CreatorType": "User", "PlaceVersion": 1, "BaseUrl": "https://localhost:2005/.127.0.0.1", "JobId": "Test", "PreferredPort": 2005}, "Arguments": {}}]
1724375040.35292,2bc8,6,GameServer,1818,13058,https://localhost:2005/.127.0.0.1,Test,https://localhost:2005,unknown,Test Executing job with mode GameServer
1724375040.35292,3828,6,GameServer,1818,13058,https://localhost:2005/.127.0.0.1,Test,https://localhost:2005,unknown,Test Fetching place 1818
https://localhost:2005/game/load-place-info
https://localhost:2005/asset/?id=1818
1724375040.57035,3828,7,GameServer,1818,13058,https://localhost:2005/.127.0.0.1,Test,https://localhost:2005,unknown,Test NetworkServer:Create
https://localhost:2005/v1.1/game-start-info/?universeId=13058
https://localhost:2005/v1.1/game-start-info/?universeId=13058
1724375041.80984,3828,7,GameServer,1818,13058,https://localhost:2005/.127.0.0.1,Test,https://localhost:2005,unknown,Test NetworkServer:Start
1724375041.84410,3828,6,GameServer,1818,13058,https://localhost:2005/.127.0.0.1,Test,https://localhost:2005,unknown,Test Started network server 127.0.0.1|2005
1724375041.96195,3828,6,GameServer,1818,13058,https://localhost:2005/.127.0.0.1,Test,https://localhost:2005,unknown,Test Finished initializing game
1724375041.96496,52b4,6,GameServer,1818,13058,https://localhost:2005/.127.0.0.1,Test,https://localhost:2005,unknown,Test Error: Script Context.RFDStarterScript:1: ')' expected near '='
        1724375041.96597,52b4,6,GameServer,1818,13058,https://localhost:2005/.127.0.0.1,Test,https://localhost:2005,unknown,Test RemoteFunction_GetServerVersion GetServerVersion
https://localhost:2005/rfd/roblox-version
https://localhost:2005/rfd/certificate
https://localhost:2005/login/negotiate.ashx?suggest=1
https://localhost:2005/game/PlaceLauncher.ashx?rcc-host-addr=127.0.0.1&rcc-port=2005&user-code=1
https://localhost:2005/game/validate-machine
https://localhost:2005/v1.0/SequenceStatistics/BatchAddToSequencesV2?apiKey=76E5A40C%2D3AE1%2D4028%2D9F10%2D7C62520BD94F
https://localhost:2005/v1.0/SequenceStatistics/BatchAddToSequencesV2?apiKey=76E5A40C%2D3AE1%2D4028%2D9F10%2D7C62520BD94F
https://localhost:2005/v1.0/SequenceStatistics/BatchAddToSequencesV2?apiKey=76E5A40C%2D3AE1%2D4028%2D9F10%2D7C62520BD94F
https://localhost:2005/v1.0/SequenceStatistics/BatchAddToSequencesV2?apiKey=76E5A40C%2D3AE1%2D4028%2D9F10%2D7C62520BD94F
https://localhost:2005/v1.1/Counters/BatchIncrement?apiKey=76E5A40C%2D3AE1%2D4028%2D9F10%2D7C62520BD94F
1724375159.46004,3b24,6,GameServer,1818,13058,https://localhost:2005/.127.0.0.1,Test,https://localhost:2005,unknown,Test FetchClientSettingsDataBlocking group "RCCService"
https://localhost:2005/rfd/roblox-version
https://localhost:2005/rfd/certificate
https://localhost:2005/login/negotiate.ashx?suggest=1
https://localhost:2005/game/PlaceLauncher.ashx?rcc-host-addr=127.0.0.1&rcc-port=2005&user-code=1
https://localhost:2005/game/validate-machine
https://localhost:2005/v1.0/SequenceStatistics/BatchAddToSequencesV2?apiKey=76E5A40C%2D3AE1%2D4028%2D9F10%2D7C62520BD94F
https://localhost:2005/v1.0/SequenceStatistics/BatchAddToSequencesV2?apiKey=76E5A40C%2D3AE1%2D4028%2D9F10%2D7C62520BD94F
https://localhost:2005/v1.1/Counters/BatchIncrement?apiKey=76E5A40C%2D3AE1%2D4028%2D9F10%2D7C62520BD94F
1724375279.87311,3b24,6,GameServer,1818,13058,https://localhost:2005/.127.0.0.1,Test,https://localhost:2005,unknown,Test FetchClientSettingsDataBlocking group "RCCService"
https://localhost:2005/api.GetAllowedSecurityVersions/?apiKey=2b4ba7fc-5843-44cf-b107-ba22d3319dcd
https://localhost:2005/api.GetAllowedMD5Hashes/?apiKey=2b4ba7fc-5843-44cf-b107-ba22d3319dcd
https://localhost:2005/v1.0/SequenceStatistics/BatchAddToSequencesV2?apiKey=76E5A40C%2D3AE1%2D4028%2D9F10%2D7C62520BD94F
https://localhost:2005/v1.0/SequenceStatistics/BatchAddToSequencesV2?apiKey=76E5A40C%2D3AE1%2D4028%2D9F10%2D7C62520BD94F
https://localhost:2005/v1.1/Counters/BatchIncrement?apiKey=76E5A40C%2D3AE1%2D4028%2D9F10%2D7C62520BD94F
1724375400.28476,3b24,6,GameServer,1818,13058,https://localhost:2005/.127.0.0.1,Test,https://localhost:2005,unknown,Test FetchClientSettingsDataBlocking group "RCCService
```

**Comment by Connorcivi** [comment]
One more thing, it hangs at validate-machine.

**Comment by Windows81** [comment]
There's an error with RFDStarterScript.  Looks like an improper
configuration.  Can you send me GameConfig.toml?

**Comment by Connorcivi** [comment]
Here it is, just know that I couldn't find a premade configuration if you had one since on the linux side it does show that it tried downloading a premade config but it failed due to 404.

```toml
server_assignment.players.maximum = 2
server_assignment.players.preferred = 2
server_assignment.instances.count = 1
game_setup.place_file.rbxl_uri = './Test.rbxl'
game_setup.roblox_version = "v348"
game_setup.persistence.sqlite_path = "./db.db"
game_setup.title = "N/A"
game_setup.description = "N/A"
game_setup.creator_name = "N/A"


retrieve_default_user_code_call_mode = "lua"
retrieve_default_user_code = '''
function(tick) -- float -> str
    return string.format('Player%d', tick)
end
'''

retrieve_username_call_mode = "lua"
retrieve_username = '''
function(user_code)
    return user_code
end
'''

retrieve_user_id_call_mode = "lua"
retrieve_user_id = '''
function(user_code)
    return math.random(1, 16777216)
end
'''

check_user_allowed_call_mode = "lua"
check_user_allowed = '''
function(user_id_num, user_code) -- string -> bool
    return true
end
'''
```

**Comment by Connorcivi** [comment]
Btw without the stuff past this line game_setup.creator_name = "N/A", same error.

**Comment by Windows81** [comment]
Got it.  That config file looks up to spec.  I know what to look for now.

**Comment by Connorcivi** [comment]
Would there be a workaround to this or just wait for an update?

**Comment by Connorcivi** [comment]
Managed to fix the connection issue now, but it keeps saying Not Authorized to join this game.

The fix was that in the RFPStarterScript, I had to disable the auto recovery thing upon boot in the rcc.py file for the Starter script and removed

_G.RFD = {["server_core.retrieve_user_id"] = (count = 0
def f(*a):
    count += 1
    return count
);}

In place with this instead

_G.RFD = {
    ["server_core.retrieve_user_id"] = function()
        local count = 0
        return function(...)
            count = count + 1
            return count
        end
    end
}

No more errors on my end for the startup process, but the authorization thing is still an issue.

**Comment by Connorcivi** [comment]
This would also probably have to be looked at,

![Screenshot 2024-08-22 230102](https://github.com/user-attachments/assets/d31c4e22-ccd9-4792-a782-3d02cd74f526)

**Comment by Windows81** [comment]
Dum plugin me.

`retrieve_user_id` has a default string value and RFD thought that it's a Lua function.  It's actually Python syntax.

Know that functions can either be written in Python or Lua.

**Comment by Windows81** [comment]
I also didn't deploy previous builds properly and the constant `GIT_RELEASE_VERSION` is set to a bad value.

**Comment by Windows81** [comment]
Consider this a gift.
https://github.com/Windows81/Roblox-Freedom-Distribution/releases/tag/0.50.1

**Comment by Connorcivi** [comment]
Morning, sorry for the late response.

So I ran the build again  and it's still saying not authorized to play the game. Is there a setting that I have to change?

**Comment by Connorcivi** [comment]
Also I do want to apologize about last night, was just tired and exhausted from doing other stuff.

**Comment by Windows81** [comment]
No problem.  I found other bugs.

And if an error shows up in the future, please send me your full verbose
logs.

**Comment by Connorcivi** [comment]
Evening,

Managed to get the server and client to finally work together a few days ago. But I noticed that modules aren't being downloaded by the server. For example, HD Admin requires a module but the server won't download it because it keeps giving out a 404 error, when I go on roblox's studio client it works immediately.

Do you have plans to make modules work? Also sounds are a bit wonky, it works sometimes and sometimes it doesn't.

**Comment by Windows81** [comment]
Some assets don't load properly.  Might be a missing user agent.

https://github.com/Windows81/Roblox-Freedom-Distribution/blob/0b04ac828c7c8a31bc5879398fb62018638d32e2/Source/assets/extract.py#L16

**Comment by Connorcivi** [comment]
I was going to suggest using an external service like roproxy.com since they force a User Agent on the server before it gets sent to roblox.com

But, reliability is an issue as these services can get shutdown at times, still trying to see if adding a user-agent is going to work.

**Comment by Connorcivi** [comment]
Python's User Agent is python-urllib3/2.2.2, which is throwing off the request to roblox.com

Still finding a way to fix this problem, will report back with a solution.

**Comment by Windows81** [comment]
Does using Roproxy solve the problem at all?

**Comment by Connorcivi** [comment]
From what I see, it depends on who your provider is, for me I used both AT&T Business and Digital Ocean.

AT&T responded to both requests from assetdelivery.roblox.com and assetdelivery.roproxy.com

But with Digital Ocean, it's different, assetdelivery.roblox.com is blocked and will not allow any IPs from that ISP. Since roproxy uses a rotating IP, they use a bunch of servers instead of one. So this causes Digital ocean to be able to read roblox through roproxy because of their rotating IPs.

In this case, try using the assetdelivery.roproxy.com services. It's not 100% reliable at times but it does the job it needs to do. Last time I heard it went down was like 2 months ago.

**Comment by Connorcivi** [comment]
I did notice something else,

Sound files aren't downloadable because roblox's servers reject access to it because the User doesn't have access to the file at all.
Public sound files are having issues as well.
