### ISSUE TITLE
Enable flags in 2021E that are enabled in later versions of Rōblox

### ISSUE THREAD

**Issue by idontyboi** [Windows81/Roblox-Freedom-Distribution#13]
I tried to run my game [a incremental game] in RFD and decided that my game has a minimum Roblox Client requirement of version 470 without sacrificing functionality. Even getting it to run on version 470 required flipping dozens, and dozens of FFlags to enable functionality that was in beta or in prototype stages at the time.

Would like to share those flags that enabling functionality in later versions of Roblox, for version 463:

| Flags | Functionality |
| --- | ----------- |
| DFFlagTheseAreSomeOfMyBestAttributes, FFlagAttributeSynchronization, FFlagStudioAttributesUI, DFFlagAttributeShortCircuit, DFFlagStricterAttributes | Enables Attribute support (needed for almost every game post-mid 2021) |
| FFlagSimCanNotTriggerTouchEvents | Enables the `BasePart.CanTouch` property  |
| FFlagSimExpandPartPhysicsApi | Likely adds ApplyAngularImpulse, ApplyImpulse and ApplyImpulseAtPosition. |
| FFlagGraphicsParticlesNewOrientations | Enables `ParticleEmitter.Orientation` property |
| FFlagParallelLua | Self explanatory. |
| FFlagTaskLibrary | Enables the initial version of task that is for Parallel Lua. |
| FFlagAutomaticSizing2 | Enables `AutomaticSize` in user interface elements. |
| FFlagEnableCloudsPhase1Beta, FFlagRenderClouds | Enables the `Clouds` instance. |
| FFlagSimSolverUniversalConstraintEnabled | Enables the `UniversalConstraint` instance. |
| FFlagTxRlEn | Recommended for connection to modern Roblox textures |
| FFlagSupportMeshPartHeads | Supports MeshPart Heads. Maybe some game will need this. |
| FFlagRaycastNestedFilterTables | Support nested filter tables in RaycastParams. |
| FFlagSimTouchEventsUseCollisionGroups | Enables the `workspace.TouchesUseCollisionGroups` property. |

These FFlags will enable functionality but RFD needs to support the APIs:
| Flags | Functionality |
| --- | ----------- |
| DFFlagAvatarEditorServiceEnabled2, DFFlagAESGetBatchItemDetailsEnabled | Enables `AvatarEditorService` |
| DFFlagPromptBundlePurchaseEnabled | Enables `MarketplaceService:PromptBundlePurchase`. |
| DFFlagTeleportAsyncEnabled | Enables `TeleportService:TeleportAsync`. |

These flags enable non-final functionality that likely isn't worth enabling since very few games will benefit without manual script changes:
| Flags | Functionality |
| --- | ----------- |
| DFFlagDataStoresV2Enabled | Enables an ALPHA version of the V2 datastore. RFD will need to be updated to support this. |
| DFFlagEnableMeshPartHeadsProperty | Enables `MeshPartHeads` property in Workspace. It's different from `MeshPartHeadsAndAccessories` and is INCOMPATIBLE with the released version. |

This will allow running for some more games. Anything newer requires hosting using Studio instead of RCC

**Comment by Windows81** [comment]
I put your flags and set all of their values, *except* for the non-final ones, to `true`.  This is the content of my `./Roblox/v463/Server/DevSettingsFile.json`:

[DevSettingsFile.json](https://github.com/user-attachments/files/17142149/DevSettingsFile.json)

**Comment by Windows81** [comment]
I also put the same flags in the client's `ClientSettings.json`.

**Comment by Windows81** [comment]
Sorry about the delay.  I'm doing a lot of refactoring and have been busy with other things.  I'm getting my master's in computer engineering right now and I'm barely out of week 5 of the first semester.

**Comment by Windows81** [comment]
The `game_container` isn't working because I'm stòópid and released an unfinished buggy build.

**Comment by Windows81** [comment]
I should have these changes released in RFD version 0.53.1.

**Comment by Windows81** [comment]
Dum.

**Comment by Windows81** [comment]
I fixed the config file last night and didn't commit to Github.  Feel free
to evaluate the file against the structure in the README.

**Comment by Windows81** [comment]
Just updated the config file now.

https://github.com/Windows81/Roblox-Freedom-Distribution/blob/353e84e8caf4d5fced498d04115cdeea53f20993/Examples/F3X%20Server/GameConfig.toml

**Comment by Windows81** [comment]
See if you get the same thing when running 2018M.

I think it might be Windows 7 working against you.

**Comment by Windows81** [comment]
I need to try it out myself, but no such problems occurred when I used
previous versions of RFD.

**Comment by Windows81** [comment]
Do you have a public IPv4 or v6 address?

I can try connecting to your 2021E server.  Maybe it'll keep me in longer.

As for the `popcnt` issue: https://www.partitionwizard.com/partitionmagic/cpu-does-not-have-popcnt.html might help.

**Comment by Windows81** [comment]
As for the `Security Timeout` problem: I patched out the `jmp` instructions that lead to them being loaded.

Can't guarantee that anything will work.

[Uploading Server.zip…]()

**Comment by Windows81** [comment]
Are you on Matrix or Discord by any chance?  I'd like to see what game you're doing.

**Comment by Windows81** [comment]
I won't add that just yet.  Let me know if anything else happens.
