### ISSUE TITLE
Update LuaU

### ISSUE THREAD

**Issue by OwlUniversal** [Windows81/Roblox-Freedom-Distribution#5]
Is it possible to update LuaU to the latest version? with support for attributes and other functions

**Comment by Windows81** [comment]
Heya.  I'm assuming that Luau comes compiled on the RCC.  To update Luau
versions, I'll need way more experience in x86 than I do now.

Also keep in mind that only 2021E supports Luau in the first place.

As a remedy: keep note of compiler errors in your scripts and remove any
use of recent type-annotation features from your game.

You can use 2024M Studio to fix that.
