### ISSUE TITLE
How to use the `rbxl` parser standalone

### ISSUE THREAD

**Issue by idontyboi** [Windows81/Roblox-Freedom-Distribution#9]
Sooo Roblox got blocked in Turkey. I am working on a game with someone, and 20 hours ago Turkey blocked Roblox for "child abuse" <they *might* have saw how bad Roblox moderation is>.

I am planning to repeatedly send and recieve .RBXL files for development using a old Studio version, but a problem: The fonts are all Arial and slightly larger!
![image](https://github.com/user-attachments/assets/2a1d06d5-1b79-4581-a5d3-f7507cda5615)

How do I use the transformer standalone so August 2024 Roblox files can open correctly on Studio V0.481.1.423973 (the last version that's friendly for low end PCs)? My PC isn't powerful enough [2GB RAM] to run a full RCC + Player at once. I know how to backport things `(PARKOUR 1.89 (2021) to 2017M, Fusion 0.3 to 2021M, CanvasDraw 3.5.2 to 2020L)` so I don't need help there

Can't find out how to do it in Guides and I'm not good enough at Python to split the serializers onto a seperate program.

**Comment by Windows81** [comment]
Thanks for stopping by!  My guides are for the executables themselves and not for the Python bootstrapper.

If you know how to run Python in a shell, do this:
```py
read_file_name = 'READ.rbxl'
write_file_name = 'WRITE.rbxl'
import assets.serialisers.rbxl as parser
open(write_file_name, 'wb').write(parser.parse(open(file_name, 'rb').read()))
```

**Comment by Windows81** [comment]
Just saw your last comment.  Fortunately, we got to address them today.
